# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.3.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

import UI.MainWindow.img_rc
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 600)
        MainWindow.setStyleSheet("#widget_Sidebar{\n"
"    background-color: rgb(204, 204, 204);\n"
"}\n"
"#widget_Sidebar QPushButton{\n"
"    border-radius: 14px;\n"
"}\n"
"#widget_Middle{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#widget_Sidebar QPushButton::pressed{\n"
"    background-color: rgb(115, 250, 121);\n"
"}\n"
"#stackedWidget_main #page_hello{\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(239, 239, 239, 255));\n"
"}\n"
"#pushButton_hello_gif{\n"
"    background-color: rgba(255, 255, 255,0);\n"
"}\n"
"#widget_page_hello{\n"
"    background-color: rgba(255, 255, 255, 128);\n"
"    border-top: 7px solid qlineargradient(y0:0, y1:1,stop: 0 rgba(214, 214, 214, 128), stop: 1 white);\n"
"    border-left: 7px solid qlineargradient(x0:0, x1:1,stop: 0 rgba(214, 214, 214, 128), stop: 1 white);\n"
"     border-bottom: 7px solid qlineargradient(y0:0, y1:1,stop: 0 white, stop: 1  rgba(214, 214, 214, 128));\n"
"    border-right: 7px solid qlineargradient(x0:0, x1:1,stop:  0 white, stop: 1 rgba(214, 214, 214, 128));\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.stackedWidget_main = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_main.setObjectName("stackedWidget_main")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.gridLayout = QtWidgets.QGridLayout(self.page_main)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_Sidebar = QtWidgets.QWidget(self.page_main)
        self.widget_Sidebar.setEnabled(True)
        self.widget_Sidebar.setMaximumSize(QtCore.QSize(105, 16777215))
        self.widget_Sidebar.setStyleSheet("")
        self.widget_Sidebar.setObjectName("widget_Sidebar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_Sidebar)
        self.verticalLayout.setContentsMargins(8, 15, 8, 15)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_Sidebar_User = QtWidgets.QPushButton(self.widget_Sidebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_Sidebar_User.sizePolicy().hasHeightForWidth())
        self.pushButton_Sidebar_User.setSizePolicy(sizePolicy)
        self.pushButton_Sidebar_User.setMinimumSize(QtCore.QSize(49, 47))
        self.pushButton_Sidebar_User.setMaximumSize(QtCore.QSize(49, 47))
        self.pushButton_Sidebar_User.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/widget_Sidebar/images/User.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Sidebar_User.setIcon(icon)
        self.pushButton_Sidebar_User.setIconSize(QtCore.QSize(47, 47))
        self.pushButton_Sidebar_User.setObjectName("pushButton_Sidebar_User")
        self.verticalLayout.addWidget(self.pushButton_Sidebar_User)
        self.pushButton_Sidebar_Home = QtWidgets.QPushButton(self.widget_Sidebar)
        self.pushButton_Sidebar_Home.setMinimumSize(QtCore.QSize(49, 47))
        self.pushButton_Sidebar_Home.setMaximumSize(QtCore.QSize(49, 47))
        self.pushButton_Sidebar_Home.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/widget_Sidebar/images/Home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Sidebar_Home.setIcon(icon1)
        self.pushButton_Sidebar_Home.setIconSize(QtCore.QSize(47, 47))
        self.pushButton_Sidebar_Home.setObjectName("pushButton_Sidebar_Home")
        self.verticalLayout.addWidget(self.pushButton_Sidebar_Home)
        self.pushButton_Sidebar_OnLine = QtWidgets.QPushButton(self.widget_Sidebar)
        self.pushButton_Sidebar_OnLine.setMinimumSize(QtCore.QSize(49, 47))
        self.pushButton_Sidebar_OnLine.setMaximumSize(QtCore.QSize(49, 47))
        self.pushButton_Sidebar_OnLine.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/widget_Sidebar/images/Online.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Sidebar_OnLine.setIcon(icon2)
        self.pushButton_Sidebar_OnLine.setIconSize(QtCore.QSize(47, 47))
        self.pushButton_Sidebar_OnLine.setObjectName("pushButton_Sidebar_OnLine")
        self.verticalLayout.addWidget(self.pushButton_Sidebar_OnLine)
        self.pushButton_Sidebar_Download = QtWidgets.QPushButton(self.widget_Sidebar)
        self.pushButton_Sidebar_Download.setMinimumSize(QtCore.QSize(49, 47))
        self.pushButton_Sidebar_Download.setMaximumSize(QtCore.QSize(49, 47))
        self.pushButton_Sidebar_Download.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/widget_Sidebar/images/Download.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Sidebar_Download.setIcon(icon3)
        self.pushButton_Sidebar_Download.setIconSize(QtCore.QSize(47, 47))
        self.pushButton_Sidebar_Download.setObjectName("pushButton_Sidebar_Download")
        self.verticalLayout.addWidget(self.pushButton_Sidebar_Download)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pushButton_Sidebar_Settings = QtWidgets.QPushButton(self.widget_Sidebar)
        self.pushButton_Sidebar_Settings.setMinimumSize(QtCore.QSize(49, 47))
        self.pushButton_Sidebar_Settings.setMaximumSize(QtCore.QSize(49, 47))
        self.pushButton_Sidebar_Settings.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/widget_Sidebar/images/Settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Sidebar_Settings.setIcon(icon4)
        self.pushButton_Sidebar_Settings.setIconSize(QtCore.QSize(47, 47))
        self.pushButton_Sidebar_Settings.setObjectName("pushButton_Sidebar_Settings")
        self.verticalLayout.addWidget(self.pushButton_Sidebar_Settings)
        self.pushButton_Sidebar_Unfold = QtWidgets.QPushButton(self.widget_Sidebar)
        self.pushButton_Sidebar_Unfold.setMinimumSize(QtCore.QSize(49, 47))
        self.pushButton_Sidebar_Unfold.setMaximumSize(QtCore.QSize(49, 47))
        self.pushButton_Sidebar_Unfold.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/widget_Sidebar/images/Shrink.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_Sidebar_Unfold.setIcon(icon5)
        self.pushButton_Sidebar_Unfold.setIconSize(QtCore.QSize(47, 47))
        self.pushButton_Sidebar_Unfold.setObjectName("pushButton_Sidebar_Unfold")
        self.verticalLayout.addWidget(self.pushButton_Sidebar_Unfold)
        self.gridLayout.addWidget(self.widget_Sidebar, 0, 0, 1, 1)
        self.widget_Middle = QtWidgets.QWidget(self.page_main)
        self.widget_Middle.setObjectName("widget_Middle")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_Middle)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.widget_Middle)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_Middle, 0, 1, 1, 1)
        self.stackedWidget_main.addWidget(self.page_main)
        self.page_hello = QtWidgets.QWidget()
        self.page_hello.setObjectName("page_hello")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_hello)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 0, 2, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 1, 3, 1, 1)
        self.widget_page_hello = QtWidgets.QWidget(self.page_hello)
        self.widget_page_hello.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_page_hello.setObjectName("widget_page_hello")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_page_hello)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_hello_text_2 = QtWidgets.QLabel(self.widget_page_hello)
        self.label_hello_text_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_hello_text_2.setObjectName("label_hello_text_2")
        self.gridLayout_4.addWidget(self.label_hello_text_2, 4, 0, 1, 1)
        self.pushButton_hello_gif = QtWidgets.QPushButton(self.widget_page_hello)
        self.pushButton_hello_gif.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/widget_Sidebar/images/MOS_Logo_gif.gif"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_hello_gif.setIcon(icon6)
        self.pushButton_hello_gif.setIconSize(QtCore.QSize(80, 80))
        self.pushButton_hello_gif.setObjectName("pushButton_hello_gif")
        self.gridLayout_4.addWidget(self.pushButton_hello_gif, 1, 0, 1, 1)
        self.label_hello_text_1 = QtWidgets.QLabel(self.widget_page_hello)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_hello_text_1.setFont(font)
        self.label_hello_text_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_hello_text_1.setObjectName("label_hello_text_1")
        self.gridLayout_4.addWidget(self.label_hello_text_1, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.widget_page_hello)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 3, 0, 1, 1)
        self.gridLayout_3.addWidget(self.widget_page_hello, 1, 2, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem4, 2, 2, 1, 1)
        self.stackedWidget_main.addWidget(self.page_hello)
        self.gridLayout_2.addWidget(self.stackedWidget_main, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget_main.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MOS Ⅲ 启动器"))
        self.label_hello_text_2.setText(_translate("MainWindow", "正在读取设置(1/10)"))
        self.label_hello_text_1.setText(_translate("MainWindow", "正在初始化启动器……"))
