# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1168, 612)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/widget_Sidebar/images/MOS_Logo_gif.gif"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("/*\n"
"    主页面qss\n"
"*/\n"
"#page_main{\n"
"    /*主页面背景*/\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"/*取消中间页面的边框*/\n"
"#stackedWidget_main_2 > QWidget\n"
"{\n"
"    border-style:none;\n"
"}\n"
"#scrollArea_page_settings{border-style:none;}\n"
"#widget_Middle{border-style:none;}\n"
"#widget_Sidebar{\n"
"    /*左边栏背景*/\n"
"    border-image: url(:/Scrub/images/Scrub_B10_V.png);\n"
"    background: rgba(255, 255, 255, 0.5);\n"
"    /*阴影 不生效 已经使用图片*/\n"
"    /*\n"
"    border-top: 5px solid qlineargradient(y0:0, y1:1,stop: 0 #ececef, stop: 1 white);\n"
"    border-left: 5px solid qlineargradient(x0:0, x1:1,stop: 0 #ececef, stop: 1 white);\n"
"     border-bottom: 5px solid qlineargradient(y0:0, y1:1,stop: 0 white, stop: 1  rgb(0, 0, 0));\n"
"    border-right: 5px solid qlineargradient(x0:0, x1:1,stop:  0 white, stop: 1 rgb(0, 0, 0));\n"
"    */\n"
"}\n"
"\n"
"/*左边边栏按钮设置*/\n"
"\n"
"#widget_Sidebar QPushButton{\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"/*账户管理页面*/\n"
"#widget_page_users_up{\n"
"    border-image: url(:/Scrub/images/Scrub_B15_FFFFFF-60_Main-User.png);\n"
"}\n"
"#stackedWidget_page_users_downPage1{\n"
"    border-image: url(:/Scrub/images/Scrub_B15_FFFFFF-60_Main-User-2.png);\n"
"}\n"
"#listWidget_users_down{\n"
"    border-radius: 8px;\n"
"    /*border: 1px solid rgb(33, 33, 33);*/\n"
"}\n"
"#listWidget_users_down QScrollBar{\n"
"    border-right: 3px solid rgba(0, 150, 255,0);\n"
"}\n"
"#listWidget_users_down QScrollBar:vertical\n"
"{\n"
"    width:12px;\n"
"    background:rgba(0,0,0,0%);\n"
"    margin:0px,0px,0px,0px;\n"
"    padding-top:9px;   /*留出9px给上面和下面的箭头*/\n"
"    padding-bottom:9px;\n"
"}\n"
"\n"
"#listWidget_users_down::item {\n"
"    height: 10px;\n"
"    padding: 12px;\n"
"    border-left: 0px solid rgba(214, 214, 214,0);\n"
"    /*border-top: 1px solid rgb(169, 169, 169);*/\n"
"    border-bottom: 1px solid rgb(169, 169, 169);\n"
"}\n"
"#listWidget_users_down::item:hover {\n"
"    background-color: rgba(235, 235, 235,0);\n"
"    border-left: 0px solid rgba(214, 214, 214,0);\n"
"    /*border-top: 1px solid rgb(214, 214, 214);*/\n"
"    border-bottom: 1px solid rgb(214, 214, 214);\n"
"}\n"
"#listWidget_users_down::item:selected {\n"
"    background-color: rgba(235, 235, 235,0);\n"
"    border-left: 0px solid rgba(214, 214, 214,0);\n"
"    /*border-top: 1px solid rgba(214, 214, 214,0);*/\n"
"    border-bottom: 1px solid rgba(214, 214, 214,0);\n"
"}\n"
"#widget_page_users_up > QPushButton{\n"
"    border-radius: 5px;\n"
"}\n"
"#widget_page_users_up_setChoice{\n"
"    border-radius: 5px;\n"
"}\n"
"\n"
"#widget_page_users_up > QPushButton::hover{\n"
"    background-color: rgba(192, 192, 192, 15%);\n"
"}\n"
"#widget_page_users_up_setChoice::hover{\n"
"    background-color: rgba(192, 192, 192, 15%);\n"
"}\n"
"#widget_page_users_up > QPushButton::pressed{\n"
"    background-color: rgba(192, 192, 192, 10%);\n"
"    color: rgb(103, 103, 103);\n"
"}\n"
"#widget_page_users_up_setChoice::pressed{\n"
"    background-color: rgb(115, 253, 255);\n"
"}\n"
"\n"
"/*主页*/\n"
"/*       游戏管理(列表)页面*/\n"
"#page_home_game > Line{\n"
"    background-color: rgb(166, 166, 166);\n"
"    border:none;\n"
"}\n"
"#widget_page_home_game_left{\n"
"    border-image: url(:/widget_Sidebar/images/Scrub_Settings-Z_B15.png);\n"
"    border-radius: 10px;\n"
"}\n"
"#widget_page_home_game_left > QPushButton{\n"
"    border-style:none;\n"
"}\n"
"#widget_page_home_game_left > QPushButton:hover{\n"
"    background-color: rgba(240, 240, 240, 191);\n"
"}\n"
"#widget_page_home_game_left > QPushButton:pressed{\n"
"    background-color: rgba(42, 130, 228, 24);\n"
"}\n"
"\n"
"#listWidget_page_home_game_left::item{\n"
"    border-left: 2px solid rgba(42, 130, 228,0);\n"
"    padding: 8px;\n"
"}\n"
"#listWidget_page_home_game_left::item:hover{\n"
"    background-color: rgba(240, 240, 240, 191);\n"
"}\n"
"#listWidget_page_home_game_left::item:selected{\n"
"    border-left: 2px solid rgb(42, 130, 228);\n"
"    background-color: rgba(42, 130, 255, 26);\n"
"}\n"
"#widget_page_home_game_right{\n"
"    border-image: url(:/widget_Sidebar/images/Scrub_Settings-Z_B15.png);\n"
"}\n"
"#listWidget_page_home_game_right_gamefile_game{\n"
"    border: 2px solid rgb(33, 33, 33);\n"
"    border-radius: 8px;\n"
"}\n"
"#listWidget_page_home_game_right_gamefile_game::item{\n"
"    height: 35px;\n"
"}\n"
"/*      游戏目录添加页面*/\n"
"#widget_home_game_file_add{\n"
"    border-image: url(:/Shadow/images/Whith_Shadow-0-2-4-0.png);\n"
"    border-radius: 5px;\n"
"}\n"
"#widget_game_file_add_ok_cancel > QPushButton{\n"
"    border-radius: 5px;\n"
"}\n"
"#pushButton_game_file_add_ok{\n"
"    background-color: rgb(42, 130, 228);\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#pushButton_game_file_add_ok:hover{\n"
"    background-color: rgb(78, 148, 228);\n"
"}\n"
"#pushButton_game_file_add_ok:pressed{\n"
"    background-color: rgb(32, 123, 228);\n"
"}\n"
"#pushButton_game_file_add_cancel{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(56, 56, 56);\n"
"}\n"
"#pushButton_game_file_add_cancel:hover{\n"
"    background-color: rgb(252, 252, 252);\n"
"    color: rgb(56, 56, 56);\n"
"}\n"
"#pushButton_game_file_add_cancel:pressed{\n"
"    background-color: rgb(243, 243, 243);\n"
"}\n"
"\n"
"/*设置页面*/\n"
"#scrollAreaWidgetContents_page_settings > QWidget\n"
"{\n"
"    border-image: url(:/widget_Sidebar/images/Scrub_Settings-Z_B15.png);\n"
"}\n"
"\n"
"\n"
"\n"
"/*\n"
"    加载页面qss\n"
"*/\n"
"#pushButton_loading_gif{\n"
"    background-color: rgba(255, 255, 255,0);\n"
"}\n"
"#widget_page_loading{\n"
"    border-radius: 20px;\n"
"    background-color: rgba(255, 255, 255,0);\n"
"    border-image: url(:/helo_loading/images/Loading_BlackGround.gif);\n"
"}\n"
"\n"
"/*\n"
"    欢迎页面qss\n"
"*/\n"
"#stackedWidget_main #page_initialize{\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:0.5, radius:0.5, fx:0.5, fy:0.5, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(233, 233, 233, 255));\n"
"}\n"
"#page_hello{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-image: url(:/hello/images/Hello_BlackGround.png);\n"
"}\n"
"#pushButton_hello_icon{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"#label_hello_text_1{\n"
"    border-image: url(:/hello/images/Hello_Text_1.png);\n"
"}\n"
"#pushButton_hello_text{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"#pushButton_hello_start{\n"
"    background-color: rgb(129, 182, 243);\n"
"    color: rgb(229, 229, 229);\n"
"    border-style:none;\n"
"}\n"
"#pushButton_hello_line{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"\n"
"/*单独控件qss*/\n"
"/*选择控件*/\n"
"QRadioButton {\n"
"    spacing: 10px;\n"
"    color: black;\n"
"    background-color:  rgba(255, 255, 255,0);\n"
"}\n"
"QRadioButton::indicator {\n"
"    background-color: rgba(255, 255, 255,0);\n"
"}\n"
"QRadioButton::indicator:unchecked {\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    border: 2px solid rgb(154, 154, 154);\n"
"    border-radius: 10px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    height: 8px;\n"
"    width: 8px;\n"
"    border: 7px solid rgb(42, 130, 228);\n"
"    border-radius: 10px;\n"
"}\n"
"QRadioButton::indicator:unchecked:hover {\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    border: 2px solid rgb(120, 120, 120);\n"
"    border-radius: 10px;\n"
"}\n"
"QRadioButton::indicator:checked:hover {\n"
"    height: 8px;\n"
"    width: 8px;\n"
"    border: 7px solid rgb(47, 144, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"QRadioButton::indicator:unchecked:pressed {\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    background-color: rgb(153, 153, 153);\n"
"    border: 2px solid rgb(84, 84, 84);\n"
"    border-radius: 10px;\n"
"}\n"
"QRadioButton::indicator:checked:pressed {\n"
"    height: 8px;\n"
"    width: 8px;\n"
"    border: 7px solid rgb(83, 163, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"\n"
"\n"
"/*QSlider*/\n"
"QSlider::groove:horizontal {\n"
"    /*滑条*/\n"
"    border: 1px solid #bbb;\n"
"    background: white;\n"
"    height: 3px;\n"
"    border-radius: 1px;\n"
"}\n"
"  \n"
"QSlider::sub-page:horizontal {\n"
"    /*已经划过的*/\n"
"    background: rgb(0, 150, 255);\n"
"    border: 1px solid rgba(255, 255, 255, 0);\n"
"    height: 3px;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal {\n"
"    /*没有划过的*/\n"
"    background: rgb(235, 235, 235);  \n"
"    border: 1px solid rgba(255, 255, 255, 0);\n"
"    height: 3px;\n"
"    border-radius: 1px;\n"
"}\n"
" \n"
"QSlider::handle:horizontal {\n"
"    /* 上下边距和左右边距(中间的“提手”)*/\n"
"    background: rgb(0, 150, 255);\n"
"    border: 5px solid rgb(0, 150, 255);\n"
"    width: 8px;\n"
"    margin-top: -8px;\n"
"    margin-bottom: -8px;\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:hover {\n"
"    background: rgb(0, 150, 255);\n"
"    border: 5px solid rgb(0, 150, 255);\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal:disabled {\n"
"    background: #bbb;\n"
"    border-color: #999;\n"
"}\n"
"\n"
"QSlider::add-page:horizontal:disabled {\n"
"    background: #eee;\n"
"    border-color: #999;\n"
"}\n"
"\n"
"QSlider::handle:horizontal:disabled {\n"
"    background: #eee;\n"
"    border: 1px solid #aaa;\n"
"    border-radius: 1px;\n"
"}\n"
"\n"
"\n"
"/*QSpinBox*/\n"
"QSpinBox {\n"
"    /* 为箭头保留空间 */\n"
"    padding-right:25px;\n"
"    border:2px solid rgb(33, 33, 33);\n"
"    background: rgba(255, 255, 255, 128);\n"
"    min-width:40px;\n"
"    border-radius: 5px;\n"
"    padding: -1;  /*改变焦点框*/\n"
"}\n"
"\n"
"QSpinBox:focus{\n"
"    /*出现光标后*/\n"
"    border:2px solid rgb(4, 51, 255);\n"
"}\n"
"\n"
"\n"
"/* 向上按钮 */\n"
"QSpinBox::up-button {\n"
"    subcontrol-origin:border;\n"
"    subcontrol-position:top right;\n"
"    width:18px;\n"
"    border-image:url(:/widget_Sidebar/images/Up.png);\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0.985075, y2:0, stop:0 rgba(235, 235, 235, 255), stop:1 rgba(255, 255, 255, 0));\n"
"    border-top-right-radius:5px;\n"
"    border-width:1px;\n"
"}\n"
" \n"
"/* 向上按钮 */\n"
"QSpinBox::up-button:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(225, 225, 225, 255), stop:1 rgba(255, 255, 255, 0));\n"
"}\n"
" \n"
"/* 向上按钮 */\n"
"QSpinBox::up-button:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:1, x2:1, y2:0, stop:0 rgba(190, 190, 190, 255), stop:1 rgba(255, 255, 255, 0));\n"
"}\n"
" \n"
"/* 向上按钮里的小箭头 */\n"
"QSpinBox::up-arrow {\n"
"    image:url(:/images/333.bmp);\n"
"    width:7px;\n"
"    height:7px;\n"
"}\n"
" \n"
"/* 向下按钮 */\n"
"QSpinBox::down-button {\n"
"    subcontrol-origin:border;\n"
"    subcontrol-position:bottom right;\n"
"    width:18px;\n"
"    border-image:url(:/widget_Sidebar/images/Dowe.png);\n"
"    border-bottom-right-radius:5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(235, 235, 235, 255), stop:1 rgba(255, 255, 255, 0));\n"
"    border-width:1px;\n"
"    border-top-width:0;\n"
"}\n"
" \n"
"/* 向下按钮 */\n"
"QSpinBox::down-button:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(225, 225, 225, 255), stop:1 rgba(255, 255, 255, 0));\n"
"}\n"
" \n"
"/* 向下按钮 */\n"
"QSpinBox::down-button:pressed {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(190, 190, 190, 255), stop:1 rgba(255, 255, 255, 0));\n"
"}\n"
" \n"
"/* 向下按钮里的小箭头 */\n"
"QSpinBox::down-arrow {\n"
"    image:url(:/images/333.bmp);\n"
"    width:7px;\n"
"    height:7px;\n"
"}\n"
"\n"
"/*设置垂直滚动条基本样式*/\n"
"QScrollBar:vertical\n"
"{\n"
"    width:8px;\n"
"    background:rgba(0,0,0,0%);\n"
"    margin:0px,0px,0px,0px;\n"
"    padding-top:9px;   /*留出9px给上面和下面的箭头*/\n"
"    padding-bottom:9px;\n"
"}\n"
"QScrollBar::handle:vertical\n"
"{\n"
"    width:8px;\n"
"    background:rgba(0,0,0,25%);\n"
"    border-radius:4px;   /*滚动条两端变成椭圆*/\n"
"    min-height:;\n"
"}\n"
"QScrollBar::handle:vertical:hover\n"
"{\n"
"    width:8px;\n"
"    background:rgba(0,0,0,50%);   /* 鼠标放到滚动条上的时候，颜色变深*/\n"
"    border-radius:4px;\n"
"    min-height:;\n"
"}\n"
"QScrollBar::add-line:vertical   /*这个应该是设置下箭头的，3.png就是箭头*/\n"
"{\n"
"    background:rgba(0,0,0,0%);\n"
"    border-style:none;\n"
"    height:9px;width:8px;\n"
"    border-image:url(:/widget_Sidebar/images/Whith-0.png);\n"
"    subcontrol-position:bottom;\n"
"}\n"
"QScrollBar::sub-line:vertical   /*设置上箭头*/\n"
"{\n"
"    background:rgba(0,0,0,0%);\n"
"    border-style:url(:/widget_Sidebar/images/Whith-0.png);\n"
"    height:9px;width:8px;\n"
"    border-image:url(:/img/caret-up_1.png);\n"
"    subcontrol-position:top;\n"
"}\n"
"QScrollBar::add-line:vertical:hover   /*当鼠标放到下箭头上的时候*/\n"
"{\n"
"    height:9px;width:8px;\n"
"    border-image:url(:/widget_Sidebar/images/Whith-0.png);\n"
"    subcontrol-position:bottom;\n"
"}\n"
"QScrollBar::sub-line:vertical:hover  /*当鼠标放到下箭头上的时候*/\n"
"{\n"
"    height:9px;width:8px;\n"
"    border-image:url(:/widget_Sidebar/images/Whith-0.png);\n"
"    subcontrol-position:top;\n"
"}\n"
" /*当滚动条滚动的时候，上面的部分和下面的部分*/\n"
"QScrollBar::add-page:vertical{\n"
"    border-radius:0px;    background:rgba(0,0,0,10%);\n"
"}\n"
"QScrollBar::sub-page:vertical  {\n"
"    border-radius:0px;    background:rgba(0,0,0,10%);\n"
"}\n"
"\n"
"QTreeWidget::item {\n"
"    height: 20px;\n"
"    padding: 8px;\n"
"    border-left: 3px solid rgba(214, 214, 214,0);\n"
"}\n"
"QTreeWidget::item:hover {\n"
"    border-left: 3px solid rgb(214, 214, 214);\n"
"    background-color: transparent;\n"
"}\n"
"QTreeWidget::item:selected {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    background-color: rgb(235, 235, 235);\n"
"    border-left: 3px solid rgb(0, 150, 255);\n"
"}\n"
"\n"
"QListWidget::item {\n"
"    height: 20px;\n"
"    padding: 8px;\n"
"}\n"
"QListWidget::item:hover {\n"
"    padding: 0px;\n"
"    background-color: transparent;\n"
"}\n"
"QListWidget::item:selected {\n"
"    padding: 0px;\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    background-color: rgb(235, 235, 235);\n"
"}\n"
"QLineEdit{\n"
"    background-color: rgb(240, 240, 240);\n"
"    border-radius: 5px;\n"
"}\n"
"QLineEdit::focus{\n"
"    border:2px solid rgb(0, 119, 255);\n"
"}\n"
"QPushButton{\n"
"    border-style:none;\n"
"    border-radius: 5px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(252, 252, 252);\n"
"}\n"
"\n"
"\n"
"*{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"*{outline:0px;}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.stackedWidget_main = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget_main.setStyleSheet("")
        self.stackedWidget_main.setObjectName("stackedWidget_main")
        self.page_main = QtWidgets.QWidget()
        self.page_main.setStyleSheet("/*模拟阴影*/\n"
"#widget_Middle > #stackedWidget_main_2{border-image: url(:/Scrub/images/Scrub_B2_FFFFFF-50_Main-M-B.png);}")
        self.page_main.setObjectName("page_main")
        self.gridLayout = QtWidgets.QGridLayout(self.page_main)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_Sidebar = QtWidgets.QWidget(self.page_main)
        self.widget_Sidebar.setEnabled(True)
        self.widget_Sidebar.setMaximumSize(QtCore.QSize(105, 16777215))
        self.widget_Sidebar.setStyleSheet("/*这个地方是点击按钮之后自动刷新(修改)的*/\n"
"#pushButton_Sidebar_Home{\n"
"    border-image: url(:/widget_Sidebar/images/Home-B-Black.png);\n"
"}")
        self.widget_Sidebar.setObjectName("widget_Sidebar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget_Sidebar)
        self.verticalLayout.setContentsMargins(0, 5, 0, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_Sidebar_Back = MyQLabel(self.widget_Sidebar)
        self.label_Sidebar_Back.setMinimumSize(QtCore.QSize(49, 47))
        self.label_Sidebar_Back.setMaximumSize(QtCore.QSize(49, 47))
        self.label_Sidebar_Back.setText("")
        self.label_Sidebar_Back.setPixmap(QtGui.QPixmap(":/widget_Sidebar/images/Back.png"))
        self.label_Sidebar_Back.setScaledContents(True)
        self.label_Sidebar_Back.setObjectName("label_Sidebar_Back")
        self.verticalLayout.addWidget(self.label_Sidebar_Back)
        self.label_Sidebar_User = MyQLabel(self.widget_Sidebar)
        self.label_Sidebar_User.setMinimumSize(QtCore.QSize(49, 47))
        self.label_Sidebar_User.setMaximumSize(QtCore.QSize(49, 47))
        self.label_Sidebar_User.setText("")
        self.label_Sidebar_User.setPixmap(QtGui.QPixmap(":/widget_Sidebar/images/User.png"))
        self.label_Sidebar_User.setScaledContents(True)
        self.label_Sidebar_User.setObjectName("label_Sidebar_User")
        self.verticalLayout.addWidget(self.label_Sidebar_User)
        self.label_Sidebar_Home = MyQLabel(self.widget_Sidebar)
        self.label_Sidebar_Home.setMinimumSize(QtCore.QSize(49, 47))
        self.label_Sidebar_Home.setMaximumSize(QtCore.QSize(49, 47))
        self.label_Sidebar_Home.setText("")
        self.label_Sidebar_Home.setPixmap(QtGui.QPixmap(":/widget_Sidebar/images/Home.png"))
        self.label_Sidebar_Home.setScaledContents(True)
        self.label_Sidebar_Home.setObjectName("label_Sidebar_Home")
        self.verticalLayout.addWidget(self.label_Sidebar_Home)
        self.label_Sidebar_OnLine = MyQLabel(self.widget_Sidebar)
        self.label_Sidebar_OnLine.setMinimumSize(QtCore.QSize(49, 47))
        self.label_Sidebar_OnLine.setMaximumSize(QtCore.QSize(49, 47))
        self.label_Sidebar_OnLine.setText("")
        self.label_Sidebar_OnLine.setPixmap(QtGui.QPixmap(":/widget_Sidebar/images/Online.png"))
        self.label_Sidebar_OnLine.setScaledContents(True)
        self.label_Sidebar_OnLine.setObjectName("label_Sidebar_OnLine")
        self.verticalLayout.addWidget(self.label_Sidebar_OnLine)
        self.label_Sidebar_Download = MyQLabel(self.widget_Sidebar)
        self.label_Sidebar_Download.setMinimumSize(QtCore.QSize(49, 47))
        self.label_Sidebar_Download.setMaximumSize(QtCore.QSize(49, 47))
        self.label_Sidebar_Download.setText("")
        self.label_Sidebar_Download.setPixmap(QtGui.QPixmap(":/widget_Sidebar/images/Download.png"))
        self.label_Sidebar_Download.setScaledContents(True)
        self.label_Sidebar_Download.setObjectName("label_Sidebar_Download")
        self.verticalLayout.addWidget(self.label_Sidebar_Download)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.label_Sidebar_Settings = MyQLabel(self.widget_Sidebar)
        self.label_Sidebar_Settings.setMinimumSize(QtCore.QSize(49, 47))
        self.label_Sidebar_Settings.setMaximumSize(QtCore.QSize(49, 47))
        self.label_Sidebar_Settings.setText("")
        self.label_Sidebar_Settings.setPixmap(QtGui.QPixmap(":/widget_Sidebar/images/Settings.png"))
        self.label_Sidebar_Settings.setScaledContents(True)
        self.label_Sidebar_Settings.setObjectName("label_Sidebar_Settings")
        self.verticalLayout.addWidget(self.label_Sidebar_Settings)
        self.gridLayout.addWidget(self.widget_Sidebar, 0, 0, 1, 1)
        self.widget_Middle = QtWidgets.QWidget(self.page_main)
        self.widget_Middle.setObjectName("widget_Middle")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_Middle)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stackedWidget_main_2 = QtWidgets.QStackedWidget(self.widget_Middle)
        self.stackedWidget_main_2.setStyleSheet("")
        self.stackedWidget_main_2.setObjectName("stackedWidget_main_2")
        self.page_users = QtWidgets.QWidget()
        self.page_users.setObjectName("page_users")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page_users)
        self.verticalLayout_4.setContentsMargins(8, -1, 8, 10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_page_users_up = QtWidgets.QWidget(self.page_users)
        self.widget_page_users_up.setObjectName("widget_page_users_up")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_page_users_up)
        self.horizontalLayout_4.setContentsMargins(12, 12, 12, 16)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_page_users_up_addUser = QtWidgets.QPushButton(self.widget_page_users_up)
        self.pushButton_page_users_up_addUser.setMinimumSize(QtCore.QSize(110, 40))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/widget_Sidebar/images/User_Page_Add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_page_users_up_addUser.setIcon(icon1)
        self.pushButton_page_users_up_addUser.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_page_users_up_addUser.setObjectName("pushButton_page_users_up_addUser")
        self.horizontalLayout_4.addWidget(self.pushButton_page_users_up_addUser)
        self.pushButton_page_users_up_refreshUser = QtWidgets.QPushButton(self.widget_page_users_up)
        self.pushButton_page_users_up_refreshUser.setMinimumSize(QtCore.QSize(96, 40))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/widget_Sidebar/images/User_Page_Refresh.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_page_users_up_refreshUser.setIcon(icon2)
        self.pushButton_page_users_up_refreshUser.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_page_users_up_refreshUser.setObjectName("pushButton_page_users_up_refreshUser")
        self.horizontalLayout_4.addWidget(self.pushButton_page_users_up_refreshUser)
        self.pushButton_page_users_up_deleteUser = QtWidgets.QPushButton(self.widget_page_users_up)
        self.pushButton_page_users_up_deleteUser.setMinimumSize(QtCore.QSize(96, 40))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/widget_Sidebar/images/User_Page_Delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_page_users_up_deleteUser.setIcon(icon3)
        self.pushButton_page_users_up_deleteUser.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_page_users_up_deleteUser.setObjectName("pushButton_page_users_up_deleteUser")
        self.horizontalLayout_4.addWidget(self.pushButton_page_users_up_deleteUser)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.widget_page_users_up_setChoice = MyQWidget(self.widget_page_users_up)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_page_users_up_setChoice.sizePolicy().hasHeightForWidth())
        self.widget_page_users_up_setChoice.setSizePolicy(sizePolicy)
        self.widget_page_users_up_setChoice.setMinimumSize(QtCore.QSize(125, 0))
        self.widget_page_users_up_setChoice.setObjectName("widget_page_users_up_setChoice")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.widget_page_users_up_setChoice)
        self.horizontalLayout_5.setContentsMargins(4, 2, 4, 2)
        self.horizontalLayout_5.setSpacing(2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_page_users_up_setChoice_icon = MyQLabel(self.widget_page_users_up_setChoice)
        self.label_page_users_up_setChoice_icon.setMaximumSize(QtCore.QSize(30, 30))
        self.label_page_users_up_setChoice_icon.setText("")
        self.label_page_users_up_setChoice_icon.setPixmap(QtGui.QPixmap(":/widget_Sidebar/images/User_Page_setChoice_Choices.png"))
        self.label_page_users_up_setChoice_icon.setScaledContents(True)
        self.label_page_users_up_setChoice_icon.setIndent(0)
        self.label_page_users_up_setChoice_icon.setObjectName("label_page_users_up_setChoice_icon")
        self.horizontalLayout_5.addWidget(self.label_page_users_up_setChoice_icon)
        self.label_page_users_up_setChoice = MyQLabel(self.widget_page_users_up_setChoice)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_page_users_up_setChoice.sizePolicy().hasHeightForWidth())
        self.label_page_users_up_setChoice.setSizePolicy(sizePolicy)
        self.label_page_users_up_setChoice.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_page_users_up_setChoice.setIndent(0)
        self.label_page_users_up_setChoice.setObjectName("label_page_users_up_setChoice")
        self.horizontalLayout_5.addWidget(self.label_page_users_up_setChoice)
        self.horizontalLayout_4.addWidget(self.widget_page_users_up_setChoice)
        self.verticalLayout_4.addWidget(self.widget_page_users_up)
        self.stackedWidget_page_users_down = QtWidgets.QStackedWidget(self.page_users)
        self.stackedWidget_page_users_down.setObjectName("stackedWidget_page_users_down")
        self.stackedWidget_page_users_downPage1 = QtWidgets.QWidget()
        self.stackedWidget_page_users_downPage1.setObjectName("stackedWidget_page_users_downPage1")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.stackedWidget_page_users_downPage1)
        self.verticalLayout_5.setContentsMargins(3, 4, 3, 8)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.listWidget_users_down = QtWidgets.QListWidget(self.stackedWidget_page_users_downPage1)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.listWidget_users_down.setFont(font)
        self.listWidget_users_down.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.listWidget_users_down.setAutoScroll(True)
        self.listWidget_users_down.setProperty("showDropIndicator", True)
        self.listWidget_users_down.setDragEnabled(False)
        self.listWidget_users_down.setDragDropOverwriteMode(False)
        self.listWidget_users_down.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.MultiSelection)
        self.listWidget_users_down.setObjectName("listWidget_users_down")
        self.verticalLayout_5.addWidget(self.listWidget_users_down)
        self.stackedWidget_page_users_down.addWidget(self.stackedWidget_page_users_downPage1)
        self.stackedWidget_page_users_downPage_loaging = QtWidgets.QWidget()
        self.stackedWidget_page_users_downPage_loaging.setObjectName("stackedWidget_page_users_downPage_loaging")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.stackedWidget_page_users_downPage_loaging)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_users_down_loading = QtWidgets.QLabel(self.stackedWidget_page_users_downPage_loaging)
        self.label_users_down_loading.setText("")
        self.label_users_down_loading.setPixmap(QtGui.QPixmap(":/Gif/images/Gif/Loaging.gif"))
        self.label_users_down_loading.setScaledContents(False)
        self.label_users_down_loading.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_users_down_loading.setObjectName("label_users_down_loading")
        self.verticalLayout_7.addWidget(self.label_users_down_loading)
        self.stackedWidget_page_users_down.addWidget(self.stackedWidget_page_users_downPage_loaging)
        self.stackedWidget_page_users_downPage_none = QtWidgets.QWidget()
        self.stackedWidget_page_users_downPage_none.setObjectName("stackedWidget_page_users_downPage_none")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.stackedWidget_page_users_downPage_none)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_users_down_none = QtWidgets.QLabel(self.stackedWidget_page_users_downPage_none)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_users_down_none.setFont(font)
        self.label_users_down_none.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_users_down_none.setObjectName("label_users_down_none")
        self.verticalLayout_6.addWidget(self.label_users_down_none)
        self.stackedWidget_page_users_down.addWidget(self.stackedWidget_page_users_downPage_none)
        self.verticalLayout_4.addWidget(self.stackedWidget_page_users_down)
        self.stackedWidget_main_2.addWidget(self.page_users)
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page_home)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.stackedWidget_page_home = QtWidgets.QStackedWidget(self.page_home)
        self.stackedWidget_page_home.setObjectName("stackedWidget_page_home")
        self.page_home_main = QtWidgets.QWidget()
        self.page_home_main.setObjectName("page_home_main")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page_home_main)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.pushButton_page_home_main_game_list = QtWidgets.QPushButton(self.page_home_main)
        self.pushButton_page_home_main_game_list.setObjectName("pushButton_page_home_main_game_list")
        self.horizontalLayout_9.addWidget(self.pushButton_page_home_main_game_list)
        self.stackedWidget_page_home.addWidget(self.page_home_main)
        self.page_home_game = QtWidgets.QWidget()
        self.page_home_game.setObjectName("page_home_game")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_home_game)
        self.horizontalLayout_7.setContentsMargins(13, 10, 13, 10)
        self.horizontalLayout_7.setSpacing(5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.widget_page_home_game_left = QtWidgets.QWidget(self.page_home_game)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_page_home_game_left.sizePolicy().hasHeightForWidth())
        self.widget_page_home_game_left.setSizePolicy(sizePolicy)
        self.widget_page_home_game_left.setMinimumSize(QtCore.QSize(155, 0))
        self.widget_page_home_game_left.setMaximumSize(QtCore.QSize(165, 16777215))
        self.widget_page_home_game_left.setObjectName("widget_page_home_game_left")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_page_home_game_left)
        self.verticalLayout_8.setContentsMargins(0, 10, 0, 10)
        self.verticalLayout_8.setSpacing(4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.stackedWidget_page_home_game_left = QtWidgets.QStackedWidget(self.widget_page_home_game_left)
        self.stackedWidget_page_home_game_left.setObjectName("stackedWidget_page_home_game_left")
        self.page_page_home_game_left_1 = QtWidgets.QWidget()
        self.page_page_home_game_left_1.setObjectName("page_page_home_game_left_1")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.page_page_home_game_left_1)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.listWidget_page_home_game_left = QtWidgets.QListWidget(self.page_page_home_game_left_1)
        self.listWidget_page_home_game_left.setIconSize(QtCore.QSize(24, 24))
        self.listWidget_page_home_game_left.setObjectName("listWidget_page_home_game_left")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_page_home_game_left.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget_page_home_game_left.addItem(item)
        self.horizontalLayout_11.addWidget(self.listWidget_page_home_game_left)
        self.stackedWidget_page_home_game_left.addWidget(self.page_page_home_game_left_1)
        self.page_page_home_game_left_2 = QtWidgets.QWidget()
        self.page_page_home_game_left_2.setObjectName("page_page_home_game_left_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.page_page_home_game_left_2)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_page_home_game_left_none = QtWidgets.QLabel(self.page_page_home_game_left_2)
        self.label_page_home_game_left_none.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_page_home_game_left_none.setWordWrap(True)
        self.label_page_home_game_left_none.setObjectName("label_page_home_game_left_none")
        self.horizontalLayout_12.addWidget(self.label_page_home_game_left_none)
        self.stackedWidget_page_home_game_left.addWidget(self.page_page_home_game_left_2)
        self.page_page_home_game_left_3 = QtWidgets.QWidget()
        self.page_page_home_game_left_3.setObjectName("page_page_home_game_left_3")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page_page_home_game_left_3)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_page_home_game_left_none_loading = QtWidgets.QLabel(self.page_page_home_game_left_3)
        self.label_page_home_game_left_none_loading.setText("")
        self.label_page_home_game_left_none_loading.setPixmap(QtGui.QPixmap(":/Gif/images/Gif/Loaging.gif"))
        self.label_page_home_game_left_none_loading.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_page_home_game_left_none_loading.setObjectName("label_page_home_game_left_none_loading")
        self.horizontalLayout_13.addWidget(self.label_page_home_game_left_none_loading)
        self.stackedWidget_page_home_game_left.addWidget(self.page_page_home_game_left_3)
        self.verticalLayout_8.addWidget(self.stackedWidget_page_home_game_left)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        self.verticalLayout_8.addItem(spacerItem2)
        self.pushButton_page_home_file_leftrefresh = QtWidgets.QPushButton(self.widget_page_home_game_left)
        self.pushButton_page_home_file_leftrefresh.setMinimumSize(QtCore.QSize(0, 32))
        self.pushButton_page_home_file_leftrefresh.setIcon(icon2)
        self.pushButton_page_home_file_leftrefresh.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_page_home_file_leftrefresh.setObjectName("pushButton_page_home_file_leftrefresh")
        self.verticalLayout_8.addWidget(self.pushButton_page_home_file_leftrefresh)
        self.pushButton_page_home_game_add = QtWidgets.QPushButton(self.widget_page_home_game_left)
        self.pushButton_page_home_game_add.setMinimumSize(QtCore.QSize(0, 32))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/widget_Sidebar/images/Game_Add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_page_home_game_add.setIcon(icon4)
        self.pushButton_page_home_game_add.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_page_home_game_add.setObjectName("pushButton_page_home_game_add")
        self.verticalLayout_8.addWidget(self.pushButton_page_home_game_add)
        self.pushButton_page_home_file_add = QtWidgets.QPushButton(self.widget_page_home_game_left)
        self.pushButton_page_home_file_add.setMinimumSize(QtCore.QSize(0, 32))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/widget_Sidebar/images/Game_File_Add.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_page_home_file_add.setIcon(icon5)
        self.pushButton_page_home_file_add.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_page_home_file_add.setObjectName("pushButton_page_home_file_add")
        self.verticalLayout_8.addWidget(self.pushButton_page_home_file_add)
        self.pushButton_page_home_game_settings = QtWidgets.QPushButton(self.widget_page_home_game_left)
        self.pushButton_page_home_game_settings.setMinimumSize(QtCore.QSize(0, 32))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/widget_Sidebar/images/Game_File_Settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_page_home_game_settings.setIcon(icon6)
        self.pushButton_page_home_game_settings.setIconSize(QtCore.QSize(20, 20))
        self.pushButton_page_home_game_settings.setObjectName("pushButton_page_home_game_settings")
        self.verticalLayout_8.addWidget(self.pushButton_page_home_game_settings)
        self.horizontalLayout_7.addWidget(self.widget_page_home_game_left)
        self.line_2 = QtWidgets.QFrame(self.page_home_game)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_7.addWidget(self.line_2)
        self.widget_page_home_game_right = QtWidgets.QWidget(self.page_home_game)
        self.widget_page_home_game_right.setObjectName("widget_page_home_game_right")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.widget_page_home_game_right)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.listWidget_page_home_game_right_gamefile_game = QtWidgets.QListWidget(self.widget_page_home_game_right)
        self.listWidget_page_home_game_right_gamefile_game.setObjectName("listWidget_page_home_game_right_gamefile_game")
        self.horizontalLayout_8.addWidget(self.listWidget_page_home_game_right_gamefile_game)
        self.horizontalLayout_7.addWidget(self.widget_page_home_game_right)
        self.stackedWidget_page_home.addWidget(self.page_home_game)
        self.page_home_game_file_add = QtWidgets.QWidget()
        self.page_home_game_file_add.setObjectName("page_home_game_file_add")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_home_game_file_add)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.widget_home_game_file_add = QtWidgets.QWidget(self.page_home_game_file_add)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_home_game_file_add.sizePolicy().hasHeightForWidth())
        self.widget_home_game_file_add.setSizePolicy(sizePolicy)
        self.widget_home_game_file_add.setObjectName("widget_home_game_file_add")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_home_game_file_add)
        self.verticalLayout_9.setContentsMargins(14, 8, 12, 12)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_home_game_file_add_h1 = QtWidgets.QLabel(self.widget_home_game_file_add)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_home_game_file_add_h1.setFont(font)
        self.label_home_game_file_add_h1.setObjectName("label_home_game_file_add_h1")
        self.verticalLayout_9.addWidget(self.label_home_game_file_add_h1)
        self.widget_home_game_file_add_2 = QtWidgets.QWidget(self.widget_home_game_file_add)
        self.widget_home_game_file_add_2.setObjectName("widget_home_game_file_add_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.widget_home_game_file_add_2)
        self.gridLayout_9.setContentsMargins(6, 2, 6, 2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButton_game_file_add_again = QtWidgets.QPushButton(self.widget_home_game_file_add_2)
        self.pushButton_game_file_add_again.setMinimumSize(QtCore.QSize(110, 27))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_game_file_add_again.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/widget_Sidebar/images/Main_Page_GameFile_AddAgain.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_game_file_add_again.setIcon(icon7)
        self.pushButton_game_file_add_again.setIconSize(QtCore.QSize(19, 19))
        self.pushButton_game_file_add_again.setObjectName("pushButton_game_file_add_again")
        self.gridLayout_9.addWidget(self.pushButton_game_file_add_again, 2, 2, 1, 1)
        self.label_home_game_file_add_file = QtWidgets.QLabel(self.widget_home_game_file_add_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_home_game_file_add_file.setFont(font)
        self.label_home_game_file_add_file.setObjectName("label_home_game_file_add_file")
        self.gridLayout_9.addWidget(self.label_home_game_file_add_file, 2, 0, 1, 1)
        self.label_home_game_file_add_file_2 = QtWidgets.QLabel(self.widget_home_game_file_add_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_home_game_file_add_file_2.setFont(font)
        self.label_home_game_file_add_file_2.setWordWrap(True)
        self.label_home_game_file_add_file_2.setObjectName("label_home_game_file_add_file_2")
        self.gridLayout_9.addWidget(self.label_home_game_file_add_file_2, 3, 0, 1, 3)
        self.label_home_game_file_add_name = QtWidgets.QLabel(self.widget_home_game_file_add_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_home_game_file_add_name.setFont(font)
        self.label_home_game_file_add_name.setObjectName("label_home_game_file_add_name")
        self.gridLayout_9.addWidget(self.label_home_game_file_add_name, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_9.addItem(spacerItem3, 2, 1, 1, 1)
        self.lineEdit_game_file_add = QtWidgets.QLineEdit(self.widget_home_game_file_add_2)
        self.lineEdit_game_file_add.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_game_file_add.setObjectName("lineEdit_game_file_add")
        self.gridLayout_9.addWidget(self.lineEdit_game_file_add, 0, 1, 1, 2)
        self.verticalLayout_9.addWidget(self.widget_home_game_file_add_2)
        self.widget_game_file_add_ok_cancel = QtWidgets.QWidget(self.widget_home_game_file_add)
        self.widget_game_file_add_ok_cancel.setObjectName("widget_game_file_add_ok_cancel")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.widget_game_file_add_ok_cancel)
        self.horizontalLayout_10.setContentsMargins(0, 2, 0, 2)
        self.horizontalLayout_10.setSpacing(12)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.pushButton_game_file_add_cancel = QtWidgets.QPushButton(self.widget_game_file_add_ok_cancel)
        self.pushButton_game_file_add_cancel.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_game_file_add_cancel.setFont(font)
        self.pushButton_game_file_add_cancel.setObjectName("pushButton_game_file_add_cancel")
        self.horizontalLayout_10.addWidget(self.pushButton_game_file_add_cancel)
        self.pushButton_game_file_add_ok = QtWidgets.QPushButton(self.widget_game_file_add_ok_cancel)
        self.pushButton_game_file_add_ok.setMinimumSize(QtCore.QSize(75, 30))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_game_file_add_ok.setFont(font)
        self.pushButton_game_file_add_ok.setObjectName("pushButton_game_file_add_ok")
        self.horizontalLayout_10.addWidget(self.pushButton_game_file_add_ok)
        self.verticalLayout_9.addWidget(self.widget_game_file_add_ok_cancel)
        self.gridLayout_8.addWidget(self.widget_home_game_file_add, 1, 1, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem5, 1, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_8.addItem(spacerItem6, 0, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_8.addItem(spacerItem7, 1, 0, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_8.addItem(spacerItem8, 2, 1, 1, 1)
        self.stackedWidget_page_home.addWidget(self.page_home_game_file_add)
        self.horizontalLayout_6.addWidget(self.stackedWidget_page_home)
        self.stackedWidget_main_2.addWidget(self.page_home)
        self.page_online = QtWidgets.QWidget()
        self.page_online.setObjectName("page_online")
        self.stackedWidget_main_2.addWidget(self.page_online)
        self.page_download = QtWidgets.QWidget()
        self.page_download.setObjectName("page_download")
        self.stackedWidget_main_2.addWidget(self.page_download)
        self.page_settings = QtWidgets.QWidget()
        self.page_settings.setStyleSheet("")
        self.page_settings.setObjectName("page_settings")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_settings)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.scrollArea_page_settings = QtWidgets.QScrollArea(self.page_settings)
        self.scrollArea_page_settings.setWidgetResizable(True)
        self.scrollArea_page_settings.setObjectName("scrollArea_page_settings")
        self.scrollAreaWidgetContents_page_settings = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_page_settings.setGeometry(QtCore.QRect(0, 0, 380, 336))
        self.scrollAreaWidgetContents_page_settings.setObjectName("scrollAreaWidgetContents_page_settings")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_page_settings)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_page_settings_h1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_page_settings)
        self.label_page_settings_h1.setScaledContents(False)
        self.label_page_settings_h1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_page_settings_h1.setObjectName("label_page_settings_h1")
        self.verticalLayout_2.addWidget(self.label_page_settings_h1)
        self.widget_page_settings_subject = QtWidgets.QWidget(self.scrollAreaWidgetContents_page_settings)
        self.widget_page_settings_subject.setObjectName("widget_page_settings_subject")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_page_settings_subject)
        self.horizontalLayout_3.setSpacing(25)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_page_settings_subject_h2 = QtWidgets.QLabel(self.widget_page_settings_subject)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_page_settings_subject_h2.setFont(font)
        self.label_page_settings_subject_h2.setObjectName("label_page_settings_subject_h2")
        self.horizontalLayout_3.addWidget(self.label_page_settings_subject_h2)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem9)
        self.radioButton_settings_subject_light = QtWidgets.QRadioButton(self.widget_page_settings_subject)
        self.radioButton_settings_subject_light.setObjectName("radioButton_settings_subject_light")
        self.horizontalLayout_3.addWidget(self.radioButton_settings_subject_light)
        self.radioButton_settings_subject_dark = QtWidgets.QRadioButton(self.widget_page_settings_subject)
        self.radioButton_settings_subject_dark.setObjectName("radioButton_settings_subject_dark")
        self.horizontalLayout_3.addWidget(self.radioButton_settings_subject_dark)
        self.radioButton_settings_subject_automatic = QtWidgets.QRadioButton(self.widget_page_settings_subject)
        self.radioButton_settings_subject_automatic.setObjectName("radioButton_settings_subject_automatic")
        self.horizontalLayout_3.addWidget(self.radioButton_settings_subject_automatic)
        self.verticalLayout_2.addWidget(self.widget_page_settings_subject)
        self.widget_page_settings_background = QtWidgets.QWidget(self.scrollAreaWidgetContents_page_settings)
        self.widget_page_settings_background.setObjectName("widget_page_settings_background")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_page_settings_background)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setVerticalSpacing(15)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.radioButton_settings_background_none = QtWidgets.QRadioButton(self.widget_page_settings_background)
        self.radioButton_settings_background_none.setEnabled(True)
        self.radioButton_settings_background_none.setObjectName("radioButton_settings_background_none")
        self.gridLayout_2.addWidget(self.radioButton_settings_background_none, 1, 0, 1, 1)
        self.radioButton_settings_background_1 = QtWidgets.QRadioButton(self.widget_page_settings_background)
        self.radioButton_settings_background_1.setObjectName("radioButton_settings_background_1")
        self.gridLayout_2.addWidget(self.radioButton_settings_background_1, 1, 1, 1, 1)
        self.radioButton_settings_background_2 = QtWidgets.QRadioButton(self.widget_page_settings_background)
        self.radioButton_settings_background_2.setObjectName("radioButton_settings_background_2")
        self.gridLayout_2.addWidget(self.radioButton_settings_background_2, 1, 2, 1, 1)
        self.radioButton_settings_background_3 = QtWidgets.QRadioButton(self.widget_page_settings_background)
        self.radioButton_settings_background_3.setObjectName("radioButton_settings_background_3")
        self.gridLayout_2.addWidget(self.radioButton_settings_background_3, 1, 3, 1, 1)
        self.radioButton_settings_background_4 = QtWidgets.QRadioButton(self.widget_page_settings_background)
        self.radioButton_settings_background_4.setObjectName("radioButton_settings_background_4")
        self.gridLayout_2.addWidget(self.radioButton_settings_background_4, 3, 0, 1, 1)
        self.radioButton_settings_background_5 = QtWidgets.QRadioButton(self.widget_page_settings_background)
        self.radioButton_settings_background_5.setObjectName("radioButton_settings_background_5")
        self.gridLayout_2.addWidget(self.radioButton_settings_background_5, 3, 1, 1, 1)
        self.radioButton_settings_background_6 = QtWidgets.QRadioButton(self.widget_page_settings_background)
        self.radioButton_settings_background_6.setObjectName("radioButton_settings_background_6")
        self.gridLayout_2.addWidget(self.radioButton_settings_background_6, 3, 2, 1, 1)
        self.radioButton_settings_background_7 = QtWidgets.QRadioButton(self.widget_page_settings_background)
        self.radioButton_settings_background_7.setObjectName("radioButton_settings_background_7")
        self.gridLayout_2.addWidget(self.radioButton_settings_background_7, 3, 3, 1, 1)
        self.label_page_settings_background_h2 = QtWidgets.QLabel(self.widget_page_settings_background)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_page_settings_background_h2.setFont(font)
        self.label_page_settings_background_h2.setObjectName("label_page_settings_background_h2")
        self.gridLayout_2.addWidget(self.label_page_settings_background_h2, 0, 0, 1, 4)
        self.verticalLayout_2.addWidget(self.widget_page_settings_background)
        self.widget_page_settings_Sidebar = QtWidgets.QWidget(self.scrollAreaWidgetContents_page_settings)
        self.widget_page_settings_Sidebar.setStyleSheet("")
        self.widget_page_settings_Sidebar.setObjectName("widget_page_settings_Sidebar")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget_page_settings_Sidebar)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_page_settings_background_h3 = QtWidgets.QLabel(self.widget_page_settings_Sidebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_page_settings_background_h3.sizePolicy().hasHeightForWidth())
        self.label_page_settings_background_h3.setSizePolicy(sizePolicy)
        self.label_page_settings_background_h3.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.label_page_settings_background_h3.setObjectName("label_page_settings_background_h3")
        self.gridLayout_7.addWidget(self.label_page_settings_background_h3, 1, 0, 1, 2)
        self.label_page_settings_sidebar_h2 = QtWidgets.QLabel(self.widget_page_settings_Sidebar)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_page_settings_sidebar_h2.setFont(font)
        self.label_page_settings_sidebar_h2.setObjectName("label_page_settings_sidebar_h2")
        self.gridLayout_7.addWidget(self.label_page_settings_sidebar_h2, 0, 0, 1, 2)
        self.horizontalSlider_page_settings_sidebar = QtWidgets.QSlider(self.widget_page_settings_Sidebar)
        self.horizontalSlider_page_settings_sidebar.setMaximum(70)
        self.horizontalSlider_page_settings_sidebar.setSingleStep(1)
        self.horizontalSlider_page_settings_sidebar.setPageStep(1)
        self.horizontalSlider_page_settings_sidebar.setProperty("value", 15)
        self.horizontalSlider_page_settings_sidebar.setSliderPosition(15)
        self.horizontalSlider_page_settings_sidebar.setTracking(True)
        self.horizontalSlider_page_settings_sidebar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_page_settings_sidebar.setObjectName("horizontalSlider_page_settings_sidebar")
        self.gridLayout_7.addWidget(self.horizontalSlider_page_settings_sidebar, 2, 0, 1, 2)
        self.spinBox_page_settings_sidebar = QtWidgets.QSpinBox(self.widget_page_settings_Sidebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_page_settings_sidebar.sizePolicy().hasHeightForWidth())
        self.spinBox_page_settings_sidebar.setSizePolicy(sizePolicy)
        self.spinBox_page_settings_sidebar.setMinimumSize(QtCore.QSize(42, 30))
        self.spinBox_page_settings_sidebar.setMouseTracking(False)
        self.spinBox_page_settings_sidebar.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.spinBox_page_settings_sidebar.setStyleSheet("")
        self.spinBox_page_settings_sidebar.setMinimum(1)
        self.spinBox_page_settings_sidebar.setMaximum(70)
        self.spinBox_page_settings_sidebar.setProperty("value", 15)
        self.spinBox_page_settings_sidebar.setObjectName("spinBox_page_settings_sidebar")
        self.gridLayout_7.addWidget(self.spinBox_page_settings_sidebar, 2, 2, 1, 1)
        self.label_page_settings_background_h3_2 = QtWidgets.QLabel(self.widget_page_settings_Sidebar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_page_settings_background_h3_2.sizePolicy().hasHeightForWidth())
        self.label_page_settings_background_h3_2.setSizePolicy(sizePolicy)
        self.label_page_settings_background_h3_2.setMinimumSize(QtCore.QSize(165, 16))
        self.label_page_settings_background_h3_2.setMaximumSize(QtCore.QSize(165, 16))
        self.label_page_settings_background_h3_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_page_settings_background_h3_2.setObjectName("label_page_settings_background_h3_2")
        self.gridLayout_7.addWidget(self.label_page_settings_background_h3_2, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.widget_page_settings_Sidebar)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem10)
        self.scrollArea_page_settings.setWidget(self.scrollAreaWidgetContents_page_settings)
        self.verticalLayout_3.addWidget(self.scrollArea_page_settings)
        self.stackedWidget_main_2.addWidget(self.page_settings)
        self.horizontalLayout.addWidget(self.stackedWidget_main_2)
        self.gridLayout.addWidget(self.widget_Middle, 0, 1, 1, 1)
        self.stackedWidget_main.addWidget(self.page_main)
        self.page_initialize = QtWidgets.QWidget()
        self.page_initialize.setObjectName("page_initialize")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_initialize)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem11, 1, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem12, 0, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem13, 1, 3, 1, 1)
        self.widget_page_loading = QtWidgets.QWidget(self.page_initialize)
        self.widget_page_loading.setMinimumSize(QtCore.QSize(161, 172))
        self.widget_page_loading.setObjectName("widget_page_loading")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_page_loading)
        self.gridLayout_4.setContentsMargins(22, 22, 22, 22)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_loading_gif = QtWidgets.QLabel(self.widget_page_loading)
        self.label_loading_gif.setMaximumSize(QtCore.QSize(80, 80))
        self.label_loading_gif.setText("")
        self.label_loading_gif.setPixmap(QtGui.QPixmap(":/widget_Sidebar/images/MOS_Logo_gif.gif"))
        self.label_loading_gif.setScaledContents(True)
        self.label_loading_gif.setObjectName("label_loading_gif")
        self.gridLayout_4.addWidget(self.label_loading_gif, 1, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem14, 1, 0, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_4.addItem(spacerItem15, 1, 2, 1, 1)
        self.label_loading_text_1 = QtWidgets.QLabel(self.widget_page_loading)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_loading_text_1.setFont(font)
        self.label_loading_text_1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_loading_text_1.setObjectName("label_loading_text_1")
        self.gridLayout_4.addWidget(self.label_loading_text_1, 2, 0, 1, 3)
        self.line = QtWidgets.QFrame(self.widget_page_loading)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 3, 0, 1, 3)
        self.label_loading_text_2 = QtWidgets.QLabel(self.widget_page_loading)
        self.label_loading_text_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_loading_text_2.setObjectName("label_loading_text_2")
        self.gridLayout_4.addWidget(self.label_loading_text_2, 4, 0, 1, 3)
        self.gridLayout_3.addWidget(self.widget_page_loading, 1, 2, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_3.addItem(spacerItem16, 2, 2, 1, 1)
        self.stackedWidget_main.addWidget(self.page_initialize)
        self.page_hello = QtWidgets.QWidget()
        self.page_hello.setObjectName("page_hello")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_hello)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem17, 2, 1, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem18, 0, 2, 3, 1)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_5.addItem(spacerItem19, 0, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem20, 0, 0, 3, 1)
        self.widget_hello = QtWidgets.QWidget(self.page_hello)
        self.widget_hello.setObjectName("widget_hello")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_hello)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setHorizontalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem21, 3, 4, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem22, 0, 3, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem23, 3, 2, 1, 1)
        self.pushButton_hello_text = QtWidgets.QPushButton(self.widget_hello)
        self.pushButton_hello_text.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/hello/images/Hello_Text.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_hello_text.setIcon(icon8)
        self.pushButton_hello_text.setIconSize(QtCore.QSize(327, 153))
        self.pushButton_hello_text.setObjectName("pushButton_hello_text")
        self.gridLayout_6.addWidget(self.pushButton_hello_text, 1, 2, 2, 3)
        self.pushButton_hello_start = QtWidgets.QPushButton(self.widget_hello)
        self.pushButton_hello_start.setMinimumSize(QtCore.QSize(173, 43))
        self.pushButton_hello_start.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/hello/images/Hello_Text_Start.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_hello_start.setIcon(icon9)
        self.pushButton_hello_start.setIconSize(QtCore.QSize(173, 43))
        self.pushButton_hello_start.setObjectName("pushButton_hello_start")
        self.gridLayout_6.addWidget(self.pushButton_hello_start, 3, 3, 2, 1)
        self.pushButton_hello_icon = QtWidgets.QPushButton(self.widget_hello)
        self.pushButton_hello_icon.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/hello/images/Hello_Logo.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_hello_icon.setIcon(icon10)
        self.pushButton_hello_icon.setIconSize(QtCore.QSize(253, 253))
        self.pushButton_hello_icon.setObjectName("pushButton_hello_icon")
        self.gridLayout_6.addWidget(self.pushButton_hello_icon, 0, 0, 6, 1)
        self.pushButton_hello_line = QtWidgets.QPushButton(self.widget_hello)
        self.pushButton_hello_line.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/hello/images/Hello_Line_Vertical.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_hello_line.setIcon(icon11)
        self.pushButton_hello_line.setIconSize(QtCore.QSize(21, 253))
        self.pushButton_hello_line.setObjectName("pushButton_hello_line")
        self.gridLayout_6.addWidget(self.pushButton_hello_line, 0, 1, 6, 1)
        spacerItem24 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_6.addItem(spacerItem24, 5, 2, 1, 3)
        self.gridLayout_5.addWidget(self.widget_hello, 1, 1, 1, 1)
        self.stackedWidget_main.addWidget(self.page_hello)
        self.horizontalLayout_2.addWidget(self.stackedWidget_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.action8 = QtGui.QAction(MainWindow)
        self.action8.setObjectName("action8")

        self.retranslateUi(MainWindow)
        self.stackedWidget_main.setCurrentIndex(1)
        self.stackedWidget_main_2.setCurrentIndex(1)
        self.stackedWidget_page_users_down.setCurrentIndex(0)
        self.stackedWidget_page_home.setCurrentIndex(1)
        self.stackedWidget_page_home_game_left.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MOS Ⅲ 启动器"))
        self.label_Sidebar_Back.setToolTip(_translate("MainWindow", "返回"))
        self.label_Sidebar_User.setToolTip(_translate("MainWindow", "用户"))
        self.label_Sidebar_Home.setToolTip(_translate("MainWindow", "主页"))
        self.label_Sidebar_OnLine.setToolTip(_translate("MainWindow", "联机"))
        self.label_Sidebar_Download.setToolTip(_translate("MainWindow", "下载"))
        self.label_Sidebar_Settings.setToolTip(_translate("MainWindow", "设置"))
        self.pushButton_page_users_up_addUser.setText(_translate("MainWindow", "添加新账号"))
        self.pushButton_page_users_up_refreshUser.setText(_translate("MainWindow", "刷新所选"))
        self.pushButton_page_users_up_deleteUser.setText(_translate("MainWindow", "删除所选"))
        self.label_page_users_up_setChoice.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:16pt;\">多选</span>/<span style=\" font-size:12pt;\">单选</span></p></body></html>"))
        self.label_users_down_none.setText(_translate("MainWindow", "没有在您电脑中读取到任何账户数据。您可以点击“添加”按钮来进行添加"))
        self.pushButton_page_home_main_game_list.setText(_translate("MainWindow", "游戏列表"))
        __sortingEnabled = self.listWidget_page_home_game_left.isSortingEnabled()
        self.listWidget_page_home_game_left.setSortingEnabled(False)
        item = self.listWidget_page_home_game_left.item(0)
        item.setText(_translate("MainWindow", "新建项目"))
        item = self.listWidget_page_home_game_left.item(1)
        item.setText(_translate("MainWindow", "新建项目"))
        self.listWidget_page_home_game_left.setSortingEnabled(__sortingEnabled)
        self.label_page_home_game_left_none.setText(_translate("MainWindow", "<html><head/><body><p>您没有添加任何游戏文件夹。</p><p style=\'line-height:22px\'>您可以点击“添加游戏文件夹”按钮来进行添加</p></body></html>"))
        self.pushButton_page_home_file_leftrefresh.setText(_translate("MainWindow", "刷新                   "))
        self.pushButton_page_home_game_add.setText(_translate("MainWindow", "安装游戏           "))
        self.pushButton_page_home_file_add.setText(_translate("MainWindow", "添加游戏文件夹"))
        self.pushButton_page_home_game_settings.setText(_translate("MainWindow", "游戏文件夹设置"))
        self.label_home_game_file_add_h1.setText(_translate("MainWindow", "添加游戏目录"))
        self.pushButton_game_file_add_again.setText(_translate("MainWindow", "重新选择"))
        self.label_home_game_file_add_file.setText(_translate("MainWindow", "游戏目录路径"))
        self.label_home_game_file_add_file_2.setText(_translate("MainWindow", "请先选择目录"))
        self.label_home_game_file_add_name.setText(_translate("MainWindow", "名称"))
        self.pushButton_game_file_add_cancel.setText(_translate("MainWindow", "取消"))
        self.pushButton_game_file_add_ok.setText(_translate("MainWindow", "保存"))
        self.label_page_settings_h1.setText(_translate("MainWindow", "个性化外观设置"))
        self.label_page_settings_subject_h2.setText(_translate("MainWindow", "主题"))
        self.radioButton_settings_subject_light.setToolTip(_translate("MainWindow", "浅色模式"))
        self.radioButton_settings_subject_light.setText(_translate("MainWindow", "浅色"))
        self.radioButton_settings_subject_dark.setToolTip(_translate("MainWindow", "深色模式"))
        self.radioButton_settings_subject_dark.setText(_translate("MainWindow", "深色"))
        self.radioButton_settings_subject_automatic.setToolTip(_translate("MainWindow", "跟随系统(只限于Mac系统)"))
        self.radioButton_settings_subject_automatic.setText(_translate("MainWindow", "跟随系统"))
        self.radioButton_settings_background_none.setText(_translate("MainWindow", "无"))
        self.radioButton_settings_background_1.setText(_translate("MainWindow", "清爽橙黄"))
        self.radioButton_settings_background_2.setText(_translate("MainWindow", "梦幻浅蓝"))
        self.radioButton_settings_background_3.setText(_translate("MainWindow", "梦幻浅红"))
        self.radioButton_settings_background_4.setText(_translate("MainWindow", "三彩斑斓"))
        self.radioButton_settings_background_5.setText(_translate("MainWindow", "深蓝天空"))
        self.radioButton_settings_background_6.setText(_translate("MainWindow", "蓝白相照"))
        self.radioButton_settings_background_7.setText(_translate("MainWindow", "粉色迷雾"))
        self.label_page_settings_background_h2.setText(_translate("MainWindow", "背景"))
        self.label_page_settings_background_h3.setText(_translate("MainWindow", "每帧间隔 (毫秒-mm)："))
        self.label_page_settings_sidebar_h2.setText(_translate("MainWindow", "左边栏动画设置"))
        self.spinBox_page_settings_sidebar.setSuffix(_translate("MainWindow", " mm"))
        self.label_page_settings_background_h3_2.setText(_translate("MainWindow", "预计 450mm (0.45s)完成"))
        self.label_loading_text_1.setText(_translate("MainWindow", "正在初始化启动器……"))
        self.label_loading_text_2.setText(_translate("MainWindow", "正在读取设置(1/3)"))
        self.action8.setText(_translate("MainWindow", "8"))
from UI.Custom_UI.QLabel import MyQLabel
from UI.Custom_UI.QWidget import MyQWidget
